// src/app/components/game-banner/game-banner.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-game-banner',
  templateUrl: './game-banner.component.html',
  styleUrls: ['./game-banner.component.scss']
})
export class GameBannerComponent implements OnInit {
  @Input() bannerUrl!: string;
  @Input() title!: string;
  @Input() adsCount: number = 0;

  constructor() { }

  ngOnInit(): void {
  }

}

<a href="" class="relative rounded-lg overflow-hidden" >
  <img src="{{ bannerUrl }}"  alt="Image Banner {{ title }}">

  <div class="w-full pt-16 pb-4 px-4 bg-game-gradient absolute bottom-0 left-0 right-0">
    <strong class="font-bold text-white block">{{ title }}</strong>
    <span class="text-zinc-300 text-sm block mt-1">{{ adsCount }} anúncio(s)</span>
  </div>
</a>

// web/src/components/GameBanner.tsx

interface GameBannerProps{
  bannerUrl: string;
  title: string;
  adsCount: number;
}

export function GameBanner({ bannerUrl, title, adsCount }: GameBannerProps) {
  return (
    <a href="" className="relative rounded-lg overflow-hidden">
          <img src={bannerUrl} alt="imagem lol" />

          <div className="w-full pt-16 pb-4 px-4 bg-game-gradient absolute bottom-0 left-0 right-0">
            <strong className="font-bold text-white block">{title}</strong>
            <span className="text-zinc-300 text-sm block mt-1">{adsCount} anúncio(s)</span>
          </div>
    </a>
  )
}
